### ISSUE TITLE
Use modular AWS SDK for JavaScript (v3)

### ISSUE THREAD

**Issue by trivikr** [typedorm/typedorm#102]
### Is your feature request related to a problem? Please describe.
The modular AWS SDK for JavaScript (v3) was made generally available [on December 15th, 2020](https://aws.amazon.com/blogs/developer/modular-aws-sdk-for-javascript-is-now-generally-available/). It also includes many frequently requested features, such as a modular packages, first-class TypeScript support and a new middleware stack.

TypeDORM [uses AWS SDK for JavaScript (v2)](https://github.com/typedorm/typedorm/blob/631b8fa2a5410c068f90b7c66d8449ab139d94a2/package.json#L23) which is expected to be deprecated.

### Describe the solution you'd like
Use modular AWS SDK for JavaScript (v3) in TypeDORM.

### Describe alternatives you've considered
Stick with AWS SDK for JavaScript (v2), as it's still fully supported and not deprecation date is announced.

### Tasks
- [x] Add Dynamodb v3 document client  
- [x] Add Document client adapter to be able to connect to v2 and v3 versions of document clients
- [x] Update Managers to call adapters instead of invoking document client methods directly
- [x] Update Tests to also use the adapter pattern
- [x] Verify that the introduction to v3 SDK support is non-breaking
- [x] Update readme explaining how to use SDK v3 client

**Comment by trivikr** [comment]
As a maintainer of AWS SDK for JavaScript, I would love to see TypeDORM merged with TypeORM instead.
The request is documented in https://github.com/typedorm/typedorm/issues/103

**Comment by whimzyLive** [comment]
@trivikr Yes that is indeed on the TODO list, but was waiting on https://github.com/aws/aws-sdk-js-v3/issues/1223 to complete. Since that's done, v3 support will soon land to TypeDORM.

**Comment by whimzyLive** [comment]
> As a maintainer of AWS SDK for JavaScript, I would love to see TypeDORM merged with TypeORM instead.
> The request is documented in #103

Anyone following this here, please refer to ["why TypeDORM can't be merged with TypeORM, at least not yet"](https://github.com/typedorm/typedorm/issues/103#issuecomment-823224630)

**Comment by imione** [comment]
@whimzyLive 
I'm looking forward to the day when TypeDORM become support aws-sdk v3.
Is there any update?
I found the feature branch [feature/102-aws-sdk-v3-support](/https://github.com/typedorm/typedorm/tree/feature/102-aws-sdk-v3-support), but the last commit was in last December, still working in progress.
I wonder that your plan to merge the branch into main.

Thank you.

**Comment by whimzyLive** [comment]
Hi @imione 

It is planned to be included in the release 1.15.0. _which was originally to happen on 31 Jan 2022_. 
We are running slightly behind the original schedule and therefore this might get delayed and pushed back to 15ish Feb., but it is likely to be available as a beta release sometime before that.

**Comment by ChristopherGillis** [comment]
Hello! It's now March. I'm running the 1.15.0 beta. Is there any chance of getting AWS SDK v3 support?

**Comment by whimzyLive** [comment]
@ChristopherGillis Apologies. There have been some blockers while adding support for V3, but they are all resolved now. V3 support will be available soon.

Keep an eye out for a new beta release over this weekend.
