### ISSUE TITLE
Add support for attribute aliasing

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#112]
# Idea
Add support for specifying attributes aliases in indexes and primary keys. Basic idea is to be able to have a static one-on-one reference between `index <-> attribute`, in cases where we would like to have indexes be a simple alias of the same type instead of being forced to `string` type.

For more info check out #109.

# Proposed Solution
entity primary key and index attributes to also support specifying entity alias, something like:
```Typescript
@Entity(
  indexes: {
    GSI1: {
      partitionKey: {
        alias: 'numberValue' // <-- this creates an alias to `numberValue` attribute on entity and will have the same type as `numberValue` 
      }, 
      sortKey: 'ORG#{{id}}#ACTIVE#{{active}}',
      type: INDEX_TYPE.GSI,
    },
  },
})
export class Organisation{
  ...
  @Attribute()
  numberValue: number;
}
```

# Tasks
- [x] update entity index primary key type infer types from entity attributes
- [x] check if the index key contains any interpolations, 
  - [x] if it does, parse it as per current impl
  - [x] if not, try to parse it as an alias by default with the same type as an aliased attribute
- [x] add test coverage
- [x] updates docs
