### ISSUE TITLE
Add entity manager `count` operation

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#119]
Add new `count` operator to entity manager, this needs to work similarly to query operation but with additional count prop.

# Tasks
- [x] add dc transformer query item to support querying only counts
- [x] update entity manager to support new count operation
- [x] add test coverage
- [x] update API and docs to include new changes
