### ISSUE TITLE
Advanced update expression support

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#123]
Add support for specifying advanced update expression options, currently, the update expression builder is limited to only "SET" based update expressions.

# Tasks
- [x] Refactor existing update expression builder to match the similar pattern as the condition expression
- [x] implicit `SET` keyword support
- [x] explicit `SET` keyword support
- [x] explicit `REMOVE` keyword support
- [x] explicit `ADD` keyword support
- [x] explicit `DELETE` keyword support
- [x] ensure that attributes referenced by indexes/primary key are properly resolved and correctly transformed
- [x] add test coverage for EM, TM, BM
- [x] document usage and API
