### ISSUE TITLE
Add an option to recalculate default values on update 

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#241]
Add support for auto-updating attribute values using configured default value provider. The current implementation of `@Attribute` allows for specifying a default value provider but there is no way to make it auto-update the value on each update.

# Tasks
- [ ] Update `@Attribute` decorator to support property `autoUpdate` - similar to `@AutoGenerateAttribute`
- [ ] Update metadata storage to store autoUpdate preference for an attribute
- [ ] Update database managers to call `defaultValue` providers everytime there is an update to the entity

A scenario where this can be useful is specified below

```typescript
import { Attribute, Entity, INDEX_TYPE } from '@typedorm/common';
import ngeohash from 'ngeohash';

import { BaseEntity } from './entity';

@Entity<IncidentEntity>({
    name: 'incident',
    primaryKey: {
        partitionKey: 'INCIDENT#{{id}}',
        sortKey: 'INCIDENT#{{id}}',
    },
    indexes: {
        gsi1: {
            partitionKey: 'INCIDENT',
            sortKey: 'INCIDENT#{{id}}',
import { Attribute, Entity, INDEX_TYPE } from '@typedorm/common';
import ngeohash from 'ngeohash';

import { BaseEntity } from './entity';

@Entity<IncidentEntity>({
    name: 'incident',
    primaryKey: {
        partitionKey: 'INCIDENT#{{id}}',
        sortKey: 'INCIDENT#{{id}}',
    },
    indexes: {
        gsi1: {
            partitionKey: 'INCIDENT',
            sortKey: 'INCIDENT#{{id}}',
            type: INDEX_TYPE.GSI,
        },
        gsi2: {
            partitionKey: 'INCIDENT',
            sortKey: '{{status}}#{{geohash}}',
            type: INDEX_TYPE.GSI,
        },
    },
})
export class IncidentEntity extends BaseEntity {
    @Attribute({
        unique: true,
    })
    id: string;

    @Attribute()
    location: {
        latitude: number;
        longitude: number;
    };

    @Attribute<IncidentEntity>({
        default: (incident) => ngeohash.encode(incident.location.latitude, incident.location.longitude, 12),
    })
    geohash: string;

    @Attribute()
    status: string;
}            type: INDEX_TYPE.GSI,
        },
        gsi2: {
            partitionKey: 'INCIDENT',
            sortKey: '{{status}}#{{geohash}}',
            type: INDEX_TYPE.GSI,
        },
    },
})
export class IncidentEntity extends BaseEntity {
    @Attribute({
        unique: true,
    })
    id: string;

    @Attribute()
    location: {
        latitude: number;
        longitude: number;
    };

    @Attribute<IncidentEntity>({
        default: (incident) => ngeohash.encode(incident.location.latitude, incident.location.longitude, 12),
    })
    geohash: string;

    @Attribute()
    status: string;
}
