### ISSUE TITLE
initial batch write/read items support

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#43]
Add initial support for batch write operations.

# Tasks

## Write support
- [x] add WriteBatch instance
- [x] add support for write operations in batch manager
- [x] add test coverage for batch manger
- [x] update docs to list usage

~## Read support~
~- [ ] add ReadBatch  instance~
~- [ ] add support for read operations in batch manager~
~- [ ] add test coverage for batch manger~
~- [ ] update docs to list usage~
This is now tracked as a separate issue here #81

**Comment by whimzyLive** [comment]
blocks #42

**Comment by whimzyLive** [comment]
This PR is included in 1.11.0-beta.1
