### ISSUE TITLE
Add Filter expression support to entity manager query 

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#56]
Add support for specifying filter expression when querying data using entity manager.

# Tasks
- [x] add filter class type to allow easy filter expression expressions
- [x] add expressions parser to parse filter options to filter instance
- [x] expression builder to support creating filter expressions from filter instances
- [x] entity manager to support filter options when querying items
- [x] update api docs
