### ISSUE TITLE
Transaction manager: add support for read transactions

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#70]
transaction manager to support read transaction
# Tasks 
- [x] Simplify Write transaction model
- [x] Add new document client transaction transcformer
- [x] Refactor transaction manger write to work operate similar to batch manager
- [x] Add support for transaction manager read support
- [x] Add test coverage
- [x] Update docs
