### ISSUE TITLE
entity manager projection support 

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#71]
Ability to specify projection expression when performing queries

# Tasks
- [x] expression builder to support building projections
- [x] `query` item projections support
- [x] `findOne` item proections support
- [x] update docs to listing potential usage
