### ISSUE TITLE
Scan manager

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#72]
Add scan manager and ability to run scan on tables 

# Tasks

- [x] add support for scan request transformation similarity to entity transformer
- [x] add support for scan response transformation
- [x] add scan manager low level `scan` operation
- [x] add scan manager find operation
- [x] add scan manager count operation
- [x] add test coverage 
- [x] update API docs to include new scan manager operations
