### ISSUE TITLE
Add stats logger

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#82]
Add stats logger to all manager,  basically idea is to capture all operation cost (i.e consumed capacity)

Useful for getting insights on how queries are performing

# Tasks 
- [x] add stats logger
- [x] refactor existing logs to support printing unique request id
- [x] add stats logging to each responses
- [x] update docs to reflect new changes
