### ISSUE TITLE
ConditionExpression support to `put` and `delete` operations

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#92]
Similarly to `Update` operation, 
add support for specifying conditions to `put` and `delete` operations.

# Tasks 

- [x] conditional put using the entity manager
- [x] conditional delete using the entity manager
- [x] conditional put using the transaction manager
- [x] conditional delete using the transaction manager
- [x] update docs
