### ISSUE TITLE
Add support for advanced condition and filter options

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#93]
Currently, We do not support performing addition, subtraction on attributes when specifying a condition or update expression, the goal of this ticket is to add support for additional `ADD` and `SUB` operators to the expression builder.

One such use case is,

`Update user's balance if it is not already zero.`

Using document client's, we can write it like:
```Typescript
updateItem({
    TableName: "MyTable",
    Key: {
        "PK": "user#alexdebrie",
        "SK": "account#0123456789"
    },
    ConditionExpression='#balance - :amount > :zero',
    UpdateExpression='SET #balance = #balance - :amount',
    ExpressionAttributeNames={
        "#balance": "balance"
    },
    ExpressionAttributeValues={
        ":amount": { "N": "<amount of transaction>" },
        ":zero": { "N": "0" },
    }
})
```

this is currently not supported when using entity manager to perform updates.

## Possible support
```Typescript
{
  where: {
     balance:  {  
       SUB: "<amount of transaction>", 
       GE: 0
     }
   }
}
```

# Tasks
- [x]  Add expression support for new arithmetic operators: ADD, SUB, MPY, DIV
- [ ] update filter expression interface to accept new operators
- [ ] update condition expression interface to accept new operators
- [ ] update expression input parser to support parsing new operators
- [ ] add test coverage
- [ ] document usage

**Comment by whimzyLive** [comment]
exp fails to validate when trying to use arithmetic operators in it. waiting on couple of sources to inform back on what's happening, until them marking it as blocked.
